name: Artemis.Plugins.Nodes.Text - Build and upload

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Artemis.Plugins.Nodes.Text/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Artemis.Plugins.Nodes.Text/Artemis.Plugins.Nodes.Text.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

