name: Build Plugins

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src

      - name: Install Plugin Uploader
        run: dotnet tool install ArtemisRGB.Tools.PluginUploader --global
        
      - name: Workshop Upload
        run: artemis-plugin-uploader upload --pat ${{ secrets.WORKSHOP_PAT }} --folder src/bin/x64/Release/net8.0/publish